### ISSUE TITLE
Files link won't work

### ISSUE THREAD

**Issue by shanefeng123** [eth-sri/lamp#1]
Hi,

In the forth step of your code prerequisites, this files download link is not working. Can you please try to fix it?

wget -r -np -R "index.html*" https://files.sri.inf.ethz.ch/lamp/

**Comment by dimy93** [comment]
Hi,
The link works for me. It might have been a temporary glitch on the side of ETH. Can you check again and confirm the issue persists?
Thank you,
Dimitar

**Comment by shanefeng123** [comment]
Hi Dimitar,

Thanks it's working now.

I read through your paper and it's excellent job. I had the similar idea but congrats on your paper.

Best,
Shane

**Comment by shanefeng123** [comment]
Hi Dimitar,

I deleted the old environment and need to download the files again. I found out that the link is not working again at the moment.

Is the server only up in working time of your office?

Best,
Shane

**Comment by dimy93** [comment]
Hi, the server we use is hosted by the computer science department of ETH. It mostly works, but they have had a few issues in the past, and I believe the first time, you were just unlucky. This time, it seems to be because they moved our files around two weeks ago, and they seem to have broken the file permissions in the process. I am working on fixing it. I am sorry for the inconvenience

**Comment by shanefeng123** [comment]
Hi Dimitar, 

No worries. Thanks for your effort. I will try to fetch it again later then.

Best,
Shane

**Comment by dimy93** [comment]
Should be fixed now

**Comment by shanefeng123** [comment]
Hi Dimitar,

Thanks. It's working on my side now.

I opened another issue about your threat model assumption. Can you please take a look as well?

Best,
Shane
